USE users;

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USER_PW VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NULL,
    LAST_LOGIN TIMESTAMP NULL,
    PREFERENCES JSON NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; -- 대소문자 구분 및 외국어 사용, 사용자 정보 안정성성

